-- INSERT into users (username, password, enabled)
-- values ('user', 'pass', 'true');
--
-- INSERT into users (username, password, enabled)
-- values ('admin', 'pass', 'true');
--
-- INSERT into authorities (username, authoritiy)
-- values ('user', ROLE_USER);
--
-- INSERT into authorities (username, authoritiy)
-- values ('admin', ROLE_ADMIN);